services:
  - type: web
    name: automatisch-main
    env: node
    repo: https://github.com/keyng-david/automatisch
    buildCommand: npm install
    startCommand: npm run build && npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: HOST
        fromService:
          name: automatisch-main
          type: web
          envVarKey: RENDER_EXTERNAL_HOSTNAME
      - key: POSTGRES_HOST
        fromDatabase:
          name: automatisch-database
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: automatisch-database
          property: port
      - key: POSTGRES_DATABASE
        fromDatabase:
          name: automatisch-database
          property: database
      - key: POSTGRES_USERNAME
        fromDatabase:
          name: automatisch-database
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: automatisch-database
          property: password
      - fromGroup: common-env-vars
databases:
  - name: automatisch-database
    databaseName: automatisch
envVarGroups:
  - name: common-env-vars
    envVars:
      - key: APP_ENV
        value: production
      - key: PROTOCOL
        value: https
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: WEBHOOK_SECRET_KEY
        generateValue: true
      - key: APP_SECRET_KEY
        generateValue: true