services:
  - type: web
    name: automatisch-main
    env: node
    repo: https://github.com/keyng-david/automatisch
    buildCommand: npm install
    startCommand: npm start
    plan: free
    nodeVersion: 18
    autoDeploy: false
    envVars:
      - key: HOST
        fromService:
          name: automatisch-main
          type: web
          envVarKey: RENDER_EXTERNAL_HOSTNAME
      - fromGroup: common-env-vars
envVarGroups:
  - name: common-env-vars
    envVars:
      - key: APP_ENV
        value: production
      - key: PROTOCOL
        value: https
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: WEBHOOK_SECRET_KEY
        generateValue: true
      - key: APP_SECRET_KEY
        generateValue: true